// Generated by CoffeeScript 1.10.0
angular.module('app').controller('DetailCtrl', ['$scope', '$location', '$rootScope', '$resource', 'sys',
    function ($scope, $location, $rootScope, $resource, sys) {
        var id = $location.$$search.id;
        var url = sys.API + '/maintenance/detail/:id/';
        var resource = $resource(url, {id: '@id'});
        var Maintenance = {
            get: resource.get,
        };

        Maintenance.get({id: id}, function (data) {
            console.log(data);
            $scope.infoTable = [
                {
                    label: '设备',
                    text: data.product,
                }, {
                    label: '固定资产编号',
                    text: data.product_id,
                }, {
                    label: '故障现象',
                    text: data.content,
                }, {
                    label: '维修时间',
                    text: data.create_time
                }
            ];

            $scope.bill = data.bill;
            $scope.images = data.logo;
            $scope.reporter = {
                screen_name: data.user.name,
                avatar_img: data.user.avatar_img,
                mobile: data.user.mobile,
            };
            $scope.store = {
                code: data.store.no,
                title: data.head_type_ + ' ' + data.store.name,
                number: data.store.tel + ' ' + data.store.phone,
                address: data.store.address,
                store_logo: data.logo[0],
            };
            $scope.fixer = {
                screen_name: data.grab_user.name,
                avatar_img: data.grab_user.avatar_img,
                mobile: data.grab_user.mobile,
                company: data.grab_user.company,
                title: data.grab_user.title,
            };
        });
        $scope.breads = [
            {
                title: '首页',
                sref: 'app'
            }, {
                title: '维修',
                sref: 'app.fix'
            }, {
                title: '工单',
                sref: 'app.fix.pending'
            }
        ];
        return $scope.timeline = {
            '2015-09-01': [
                {
                    label: 'Report',
                    user: 'Mr David',
                    mobile: '18721349873',
                    time: '10: 27'
                }, {
                    label: 'Push',
                    user: 'Mr bing',
                    title: 'Chairman',
                    mobile: '18721349854',
                    time: '10: 30'
                }, {
                    label: 'Received',
                    user: 'Mr Bang',
                    title: 'Goodman',
                    mobile: '18721349843',
                    time: '10: 40'
                }, {
                    label: 'Got',
                    user: 'Mr Bang',
                    title: 'Goodman',
                    mobile: '18721349843',
                    time: '10: 20'
                }
            ],
            '2015-09-02': [
                {
                    label: 'Report',
                    user: 'Mr David',
                    mobile: '18721349873',
                    time: '10: 27'
                }, {
                    label: 'Push',
                    user: 'Mr bing',
                    title: 'Chairman',
                    mobile: '18721349854',
                    time: '10: 30'
                }, {
                    label: 'Received',
                    user: 'Mr Bang',
                    title: 'Goodman',
                    mobile: '18721349843',
                    time: '10: 40'
                }, {
                    label: 'Got',
                    user: 'Mr Bang',
                    title: 'Goodman',
                    mobile: '18721349843',
                    time: '10: 20'
                }
            ],
            'Present': [
                {
                    text: 'charging'
                }
            ]
        };
    }]);
